### ISSUE TITLE
All internal links are broken

### ISSUE THREAD

**Issue by johnspackman** [apostrophecms/apostrophe-documentation#143]
All the internal lnks are broken - for example go to https://docs.apostrophecms.org/apostrophe/modules/apostrophe-doc-type-manager and click on the link to apostrophe-module at the top of the page.

Many (all?) of the other links in the pages are broken too, the only ones that work properly seem to be those created by gitbook.

**Comment by stuartromanek** [comment]
As far as I can tell the broken links were contained to the module reference (`/modules`) .. These links were generated from documentation comments and not properly formatted in the move to gitbook.

There are a few places this is broken, but now the automatically generated ones (like your case illustrates) are fixed in production.

There is still some manual work needed around this ...

**Comment by stuartromanek** [comment]
oh, @johnspackman if you are finding broken links outside the `/modules` portion of the doc, please open another issue! thanks!

**Comment by stuartromanek** [comment]
fixed all the core references to the old docs I could find .. @johnspackman please open specific issues if you find anything else. Thanks!
