### ISSUE TITLE
Failed to add ckeditor (easyimage plugin)

### ISSUE THREAD

**Issue by joingit947** [apostrophecms/apostrophe-documentation#304]
After reading all the information from the Internet of ckeditor, I still unable to add the easyimage plugin into the ckeditor4.

What I have done: 
I have dowloaded the easyimage plugin and its associates ............ and updated the config file, but the CMS image function still locked up (didn't allow me to perform further editing such as resizing, draging).

Please help if you could.

I think I am lack of some detail steps .................. I am NOT a smart user (please help me out). THANK YOU.

**Comment by boutell** [comment]
Have you been through this page?

https://docs.apostrophecms.org/howtos/ckeditor.html

But let me add: i don't think easyimage is a good fit for Apostrophe. Apostrophe already offers a media library, resizes your images to appropriate sizes, provides slideshow widgets, etc. You should use that functionality, rather than pushing in another direction.

Let us know your thoughts on that after you try those capabilities.

**Comment by joingit947** [comment]
Dear Tom,
How nice to hear from you.
I'll install ApostropheCMS, and work on it.
Appreciate and thanks.
Best Regards,Abbott
    Tom Boutell (<notifications@github.com>) 在 2020年8月18日星期二 下午10:18:05 [GMT+8] 寫道：  
 
 


Have you been through this page?

https://docs.apostrophecms.org/howtos/ckeditor.html

But let me add: i don't think easyimage is a good fit for Apostrophe. Apostrophe already offers a media library, resizes your images to appropriate sizes, provides slideshow widgets, etc. You should use that functionality, rather than pushing in another direction.

Let us know your thoughts on that after you try those capabilities.
